services:
  - type: web
    name: Linkbypass-bot
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: PORT
        value: 10000
